version: "{build}"

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"

init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

install:
  - pip install -U pip
  - pip install -U -r dev_requirements.txt

build: off

test_script:
  - set TEST_PACKAGING=1
  - python -m coverage run --branch --source . -m unittest discover --verbose

after_test:
  - python -m coverage report --show-missing
  - codecov
